# Generated by Django 5.0.4 on 2024-05-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('phone', models.CharField(default='test', max_length=16)),
                ('address', models.CharField(max_length=100, verbose_name='Почтовый адрес')),
            ],
            options={
                'verbose_name': 'контактная информация',
                'verbose_name_plural': 'контактная информация',
                'ordering': ('phone',),
            },
        ),
    ]
